// Code generated by goctl. DO NOT EDIT.
package types

type BFFRequest struct {
	UserId  int64 `json:"userId"`
	GoodsId int64 `json:"goodsId"`
	Num     int64 `json:"num"`
	PayType int64 `json:"payType"`
}

type CreateOrderRequest struct {
	UserId  int64 `json:"userId"`
	GoodsId int64 `json:"goodsId"`
	Num     int64 `json:"num"`
	PayType int64 `json:"payType"`
}

type Response struct {
	Code int                    `json:"code"`
	Msg  string                 `json:"msg"`
	Data map[string]interface{} `json:"data"`
}
