// Code generated by goctl. DO NOT EDIT.
// Source: order.proto

package server

import (
	"context"

	"order/internal/logic"
	"order/internal/svc"
	"order/order"
)

type OrderServer struct {
	svcCtx *svc.ServiceContext
	order.UnimplementedOrderServer
}

func NewOrderServer(svcCtx *svc.ServiceContext) *OrderServer {
	return &OrderServer{
		svcCtx: svcCtx,
	}
}

func (s *OrderServer) TranCreateOrder(ctx context.Context, in *order.TranCreateOrderRequest) (*order.Response, error) {
	l := logic.NewTranCreateOrderLogic(ctx, s.svcCtx)
	return l.TranCreateOrder(in)
}

func (s *OrderServer) TranRollback(ctx context.Context, in *order.TranDelOrderRequest) (*order.Response, error) {
	l := logic.NewTranRollbackLogic(ctx, s.svcCtx)
	return l.TranRollback(in)
}

func (s *OrderServer) CreateOrder(ctx context.Context, in *order.TranCreateOrderRequest) (*order.Response, error) {
	l := logic.NewCreateOrderLogic(ctx, s.svcCtx)
	return l.CreateOrder(in)
}
