// Code generated by goctl. DO NOT EDIT.
// Source: stock.proto

package server

import (
	"context"

	"stock/internal/logic"
	"stock/internal/svc"
	"stock/stock"
)

type StockServer struct {
	svcCtx *svc.ServiceContext
	stock.UnimplementedStockServer
}

func NewStockServer(svcCtx *svc.ServiceContext) *StockServer {
	return &StockServer{
		svcCtx: svcCtx,
	}
}

func (s *StockServer) TranUpdateInventory(ctx context.Context, in *stock.TranUpdateInventoryRequest) (*stock.Response, error) {
	l := logic.NewTranUpdateInventoryLogic(ctx, s.svcCtx)
	return l.TranUpdateInventory(in)
}

func (s *StockServer) TranUpdateInventoryRollback(ctx context.Context, in *stock.TranUpdateInventoryRequest) (*stock.Response, error) {
	l := logic.NewTranUpdateInventoryRollbackLogic(ctx, s.svcCtx)
	return l.TranUpdateInventoryRollback(in)
}
